### PR TITLE
do not call pwd or dirname when not needed ... optimize for being dir…

### PR DESCRIPTION
**Pull request by grosser**
…ectly on top of Gemfile

makes `time ruby -v` ~3-4ms faster

@gma

### CODE REVIEW

**Comment by gma** [comment]
Hi Michael. Thanks for these two PRs, I always appreciate people going to the effort to submit them.

I like the move from `$(pwd)` to `$PWD`, and would apply a patch that just made that change. `$PWD` would need quoting though, to support directories with spaces or shell meta characters in their names.

I prefer `while [ "$(dirname $dir)" != "/" ]` to `while true` though; I think it makes it easier to grasp how the function works.

**Comment by grosser** [comment]
https://github.com/gma/bundler-exec/pull/35 for the pwd change

I changed it to `while true` so `dirname` gets called 1 less time wherever the Gemfile may be.

Could change it to this, if having Gemfile in root is a not required:
```
    while [ $dir == "/" ]; do
        [ -f "$dir/Gemfile" ] && return
        dir="$(dirname $dir)"
    done
```

**Comment by grosser** [comment]
ah nvm ... that was never supported ... changed it :)
... also using `return` in both cases so it's a bit more symmetric

**Comment by gma** [comment]
True, that would work with the proviso that `Gemfile` wasn't in `/`. But we don't know that people don't do that. And I suspect that some people using Docker do actually have that situation. Maybe not on purpose, but I bet it's out there.

Given that it saves less than 4ms, I'm not keen to introduce a patch that changes behaviour, when it's such a tiny benefit. Sorry.

**Comment by gma** [comment]
What's the `nvm` thing? I'm afraid I'm not following that bit.

**Comment by gma** [comment]
Don't worry, I'm working up a commit. I had more quoting related comments, then realised that you haven't changed the behaviour anyway, so I'm just making the changes. Will be 5 minutes...

**Comment by gma** [comment]
Closing this as I've made the changes manually on `master`. Cheers!

**Comment by grosser** [comment]
awesome, thx!

**Pull request closed without merging**
