### PR TITLE
add rails into BUNDLED_COMMANDS

### PR DESCRIPTION
**Pull request by aki2o**
I'd like to execute `rails` command too without `bundle exec`

### CODE REVIEW

**Comment by gma** [comment]
Thanks!

**Comment by aki2o** [comment]
Oh... sorry, this patch seems bad by #21

**Comment by gma** [comment]
Ah, I'd totally forgotten about that. I'm sure it doesn't hurt to execute it with `bundle exec`, but it will slow it down a little bit, so I'll revert. Thanks for pointing that out…

**Comment by aki2o** [comment]
It seems that bundler already includes the patch for #21 .
So,  `bundle exec rails` is no problem, isn't it?

If so, I hope this patch is not reverted...

**Comment by gma** [comment]
What the article referred to in #21 says is that the `rails` command takes care of loading Bundler itself, before it loads any other gems.

That means we don't need to execute `rails` with `bundle exec`. It's therefore better not to do it, as running `bundle exec` slows down a command's startup time ever so slightly.

**Pull request merged**
